-- Insert Categories
INSERT INTO categories (name)
VALUES ('Beverages'),
       ('Dairy'),
       ('Bakery'),
       ('Snacks'),
       ('Frozen Foods'),
       ('Produce'),
       ('Meat'),
       ('Seafood'),
       ('Household'),
       ('Personal Care');

-- Insert Products
INSERT INTO products (name, price, description, category_id)
VALUES ('Coca-Cola Classic 1.5L',
        2.99,
        'Refreshing carbonated soft drink with the original Coca-Cola taste.',
        1),
       ('Anchor Full Cream Milk 1L',
        3.49,
        'Fresh full cream milk rich in calcium and protein.',
        2),
       ('Whole Wheat Bread',
        2.50,
        'Healthy whole wheat bread baked fresh daily.',
        3),
       ('Lay''s Classic Potato Chips 200g',
        4.25,
        'Crispy salted potato chips perfect for snacking.',
        4),
       ('Birds Eye Frozen Mixed Vegetables 500g',
        5.75,
        'Frozen mix of carrots, peas, and corn for quick meals.',
        5),
       ('Fresh Bananas 1kg',
        1.99,
        'Naturally sweet fresh bananas sourced from local farms.',
        6),
       ('Chicken Breast Fillet 1kg',
        8.99,
        'Fresh boneless skinless chicken breast fillets.',
        7),
       ('Atlantic Salmon Fillet 500g',
        12.50,
        'Premium fresh Atlantic salmon fillet rich in omega-3.',
        8),
       ('Dettol Antibacterial Surface Cleaner 500ml',
        6.20,
        'Powerful antibacterial cleaner for household surfaces.',
        9),
       ('Dove Deep Moisture Body Wash 400ml',
        7.10,
        'Moisturizing body wash for soft and healthy skin.',
        10);